---
engines:
  duplication:
    enabled: true
    exclude_fingerprints:
    - 0e16666415e2499b8929a76107e1e170
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    config:
      config: test/fixtures/config/.eslintrc
  fixme:
    enabled: true
ratings:
  paths:
  - "src/**.js"
exclude_paths:
- test/
- docs/
- index*.js
